### ISSUE TITLE
Dashmap get_mut sometimes block thread

### ISSUE THREAD

**Issue by Kumassy** [Kumassy/ownserver#33]
In certain situation, `get_mut` exhausts entire CPU. 
https://github.com/Kumassy/ownserver/blob/9830786a2dcfa1c30d3123a52a016692d8fb3a99/proxy_server/src/store.rs#L22-L29

Use `try_get_mut` of DashMap 5
https://docs.rs/dashmap/latest/dashmap/struct.DashMap.html#method.try_get_mut

**Comment by x1957** [comment]
> In async code, dashmap sometimes causes deadlock
> 
> > This is a known issue. It stems from the fact that you are keeping a Ref guard bound to _ across an await point which may deadlock. The v4 release does fix this issue and will be coming out in May.
> 
> [xacrimon/dashmap#79](https://github.com/xacrimon/dashmap/issues/79)
> 
> DashMap 5.3.4 still have the problem, so we should use `RwLock<HashMap<K,V>>` for now.

Does 5.4 still have the problem?
