### ISSUE TITLE
udpとtcpを同時に公開したい(GeyserMC対応)

### ISSUE THREAD

**Issue by creeper-0910** [Kumassy/ownserver#46]
複数のissue立て申し訳ありません。
GeyserMCを用いてクロスプレイサーバーを立てたいと考えているのですが、tcpとudpの同時公開に対応していただくことはできますでしょうか？
よろしくお願いいたします。

**Comment by Kumassy** [comment]
https://github.com/Kumassy/ownserver/pull/53 で対応しました。
また #56 で同じ Issue が来たので、こちらは close して #56 で対応します
